// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// geo_point_in_polygon_cpp
LogicalVector geo_point_in_polygon_cpp(NumericVector x, NumericVector y, NumericVector poly_x, NumericVector poly_y);
RcppExport SEXP _geo_geo_point_in_polygon_cpp(SEXP xSEXP, SEXP ySEXP, SEXP poly_xSEXP, SEXP poly_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type poly_x(poly_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type poly_y(poly_ySEXP);
    rcpp_result_gen = Rcpp::wrap(geo_point_in_polygon_cpp(x, y, poly_x, poly_y));
    return rcpp_result_gen;
END_RCPP
}
// geo_point_in_multipolygon_cpp
LogicalVector geo_point_in_multipolygon_cpp(NumericVector x, NumericVector y, NumericVector poly_x, NumericVector poly_y, IntegerVector lxv);
RcppExport SEXP _geo_geo_point_in_multipolygon_cpp(SEXP xSEXP, SEXP ySEXP, SEXP poly_xSEXP, SEXP poly_ySEXP, SEXP lxvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type poly_x(poly_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type poly_y(poly_ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type lxv(lxvSEXP);
    rcpp_result_gen = Rcpp::wrap(geo_point_in_multipolygon_cpp(x, y, poly_x, poly_y, lxv));
    return rcpp_result_gen;
END_RCPP
}
// geo_clip_polyline_to_rect_cpp
List geo_clip_polyline_to_rect_cpp(NumericVector x, NumericVector y, double xmin, double xmax, double ymin, double ymax);
RcppExport SEXP _geo_geo_clip_polyline_to_rect_cpp(SEXP xSEXP, SEXP ySEXP, SEXP xminSEXP, SEXP xmaxSEXP, SEXP yminSEXP, SEXP ymaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< double >::type xmax(xmaxSEXP);
    Rcpp::traits::input_parameter< double >::type ymin(yminSEXP);
    Rcpp::traits::input_parameter< double >::type ymax(ymaxSEXP);
    rcpp_result_gen = Rcpp::wrap(geo_clip_polyline_to_rect_cpp(x, y, xmin, xmax, ymin, ymax));
    return rcpp_result_gen;
END_RCPP
}
// geo_clip_polyline_to_polygon_cpp
List geo_clip_polyline_to_polygon_cpp(NumericVector x, NumericVector y, NumericVector poly_x, NumericVector poly_y);
RcppExport SEXP _geo_geo_clip_polyline_to_polygon_cpp(SEXP xSEXP, SEXP ySEXP, SEXP poly_xSEXP, SEXP poly_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type poly_x(poly_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type poly_y(poly_ySEXP);
    rcpp_result_gen = Rcpp::wrap(geo_clip_polyline_to_polygon_cpp(x, y, poly_x, poly_y));
    return rcpp_result_gen;
END_RCPP
}
// geo_pointkriging_impl_cpp
List geo_pointkriging_impl_cpp(NumericVector lat, NumericVector lon, NumericVector z, NumericVector latgr, NumericVector longr, NumericVector vgr, int maxnumber, double maxdist, int option, int minnumber, double mz, int zeroset, int varcalc, double sill, IntegerVector reitur, int n, int m, IntegerVector stdcrt, IntegerVector stdrrt, IntegerVector dir, IntegerVector i1, double rat, IntegerVector treitur, Nullable<IntegerVector> isub, Nullable<IntegerVector> isubgr, int subareas, int xy, int suboption);
RcppExport SEXP _geo_geo_pointkriging_impl_cpp(SEXP latSEXP, SEXP lonSEXP, SEXP zSEXP, SEXP latgrSEXP, SEXP longrSEXP, SEXP vgrSEXP, SEXP maxnumberSEXP, SEXP maxdistSEXP, SEXP optionSEXP, SEXP minnumberSEXP, SEXP mzSEXP, SEXP zerosetSEXP, SEXP varcalcSEXP, SEXP sillSEXP, SEXP reiturSEXP, SEXP nSEXP, SEXP mSEXP, SEXP stdcrtSEXP, SEXP stdrrtSEXP, SEXP dirSEXP, SEXP i1SEXP, SEXP ratSEXP, SEXP treiturSEXP, SEXP isubSEXP, SEXP isubgrSEXP, SEXP subareasSEXP, SEXP xySEXP, SEXP suboptionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lat(latSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type latgr(latgrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type longr(longrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vgr(vgrSEXP);
    Rcpp::traits::input_parameter< int >::type maxnumber(maxnumberSEXP);
    Rcpp::traits::input_parameter< double >::type maxdist(maxdistSEXP);
    Rcpp::traits::input_parameter< int >::type option(optionSEXP);
    Rcpp::traits::input_parameter< int >::type minnumber(minnumberSEXP);
    Rcpp::traits::input_parameter< double >::type mz(mzSEXP);
    Rcpp::traits::input_parameter< int >::type zeroset(zerosetSEXP);
    Rcpp::traits::input_parameter< int >::type varcalc(varcalcSEXP);
    Rcpp::traits::input_parameter< double >::type sill(sillSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type reitur(reiturSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type stdcrt(stdcrtSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type stdrrt(stdrrtSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dir(dirSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type i1(i1SEXP);
    Rcpp::traits::input_parameter< double >::type rat(ratSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type treitur(treiturSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type isub(isubSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type isubgr(isubgrSEXP);
    Rcpp::traits::input_parameter< int >::type subareas(subareasSEXP);
    Rcpp::traits::input_parameter< int >::type xy(xySEXP);
    Rcpp::traits::input_parameter< int >::type suboption(suboptionSEXP);
    rcpp_result_gen = Rcpp::wrap(geo_pointkriging_impl_cpp(lat, lon, z, latgr, longr, vgr, maxnumber, maxdist, option, minnumber, mz, zeroset, varcalc, sill, reitur, n, m, stdcrt, stdrrt, dir, i1, rat, treitur, isub, isubgr, subareas, xy, suboption));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_geo_geo_point_in_polygon_cpp", (DL_FUNC) &_geo_geo_point_in_polygon_cpp, 4},
    {"_geo_geo_point_in_multipolygon_cpp", (DL_FUNC) &_geo_geo_point_in_multipolygon_cpp, 5},
    {"_geo_geo_clip_polyline_to_rect_cpp", (DL_FUNC) &_geo_geo_clip_polyline_to_rect_cpp, 6},
    {"_geo_geo_clip_polyline_to_polygon_cpp", (DL_FUNC) &_geo_geo_clip_polyline_to_polygon_cpp, 4},
    {"_geo_geo_pointkriging_impl_cpp", (DL_FUNC) &_geo_geo_pointkriging_impl_cpp, 28},
    {NULL, NULL, 0}
};

RcppExport void R_init_geo(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
