# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

geo_point_in_polygon_cpp <- function(x, y, poly_x, poly_y) {
    .Call('_geo_geo_point_in_polygon_cpp', PACKAGE = 'geo', x, y, poly_x, poly_y)
}

geo_point_in_multipolygon_cpp <- function(x, y, poly_x, poly_y, lxv) {
    .Call('_geo_geo_point_in_multipolygon_cpp', PACKAGE = 'geo', x, y, poly_x, poly_y, lxv)
}

geo_clip_polyline_to_rect_cpp <- function(x, y, xmin, xmax, ymin, ymax) {
    .Call('_geo_geo_clip_polyline_to_rect_cpp', PACKAGE = 'geo', x, y, xmin, xmax, ymin, ymax)
}

geo_clip_polyline_to_polygon_cpp <- function(x, y, poly_x, poly_y) {
    .Call('_geo_geo_clip_polyline_to_polygon_cpp', PACKAGE = 'geo', x, y, poly_x, poly_y)
}

geo_pointkriging_impl_cpp <- function(lat, lon, z, latgr, longr, vgr, maxnumber, maxdist, option, minnumber, mz, zeroset, varcalc, sill, reitur, n, m, stdcrt, stdrrt, dir, i1, rat, treitur, isub = NULL, isubgr = NULL, subareas = 0L, xy = 0L, suboption = 1L) {
    .Call('_geo_geo_pointkriging_impl_cpp', PACKAGE = 'geo', lat, lon, z, latgr, longr, vgr, maxnumber, maxdist, option, minnumber, mz, zeroset, varcalc, sill, reitur, n, m, stdcrt, stdrrt, dir, i1, rat, treitur, isub, isubgr, subareas, xy, suboption)
}
